### ISSUE TITLE
Add Preference to announce table position when navigating by cell

### ISSUE THREAD

**Issue by FS-ASmith** [NSoiffer/MathCAT#168]
When navigating by cell in a table, it would be nice to hear row and column announcements, such as "Row 0 Column 1".  This could also be spoken when on a cell root and ReadCurrent is invoked.  This could be a preference setting, since some may find it too verbose.  Alternatively, there could be an API method to get the current cell coordinates, and then applications could display/speak that information however they wish.

**Comment by NSoiffer** [comment]
If `NavVerbosity` is set to `Verbose`, it does say these. As an example, "move left, column 2; negative 7". Here's the rule for moving to the left in Navigations.yaml:
```
- name: move-cell-previous
  tag: mtd
  match: "$NavCommand='MoveCellPrevious'"
  replace:
  - test:
      if: "preceding-sibling::*"
      then:
      - test:
          if: "$NavVerbosity = 'Verbose'"
          then:
          - t: "move left"
          - pause: short
          - t: "column"
          - x: "count(preceding-sibling::*)"
          - pause: medium
      - test:
          if: "$NavMode='Character'"
          then:
          - with:
              variables: [NavCommand: "'MovePreviousZoom'"]
              replace: [x: "preceding-sibling::*[1]"]
          else:
          - set_variables: [NavNode: "preceding-sibling::*[1]/*[1]/@id"]
      else:
      - t: "no previous column"
      - set_variables: [SpeakExpression: "'false'"]
```

Typically,  `NavVerbosity=Verbose` causes the command to be echoed. I think it might make sense to speak the row/col # for `Medium`, and leave `Terse` as just saying the contents.

Thoughts?
