### ISSUE TITLE
speed up reading unicode-full.yaml file

### ISSUE THREAD

**Issue by NSoiffer** [NSoiffer/MathCAT#86]
I cut the size of the file from 10,000 lines to 4,000 lines. It took as long to read in/process. I finally broke down and did some profiling. ~25% of the time to get the first phrase out (that requires unicode-full.yaml) is compiling xpaths (`sxd_xpath::Factory::build`). This is called from `MyXPath::build`, and `MyXPath` has a `clone` method. Using that, I can think of two ideas to speed up reading:
1. Use a cache that translates the string to the resulting xpath (this might be a dictionary or a larger cache as even a range my have many translations in it (see example below)
2. For the range, compile the "raw" range and keep track of the XPaths and where there are substitutions and then copy everything that isn't a substitution.

The catch is that MyXPath's clone method calls `sxd_xpath::Factory::build` because XPath's can't be cloned. I don't think adding `clone` to the xpath implementation is an option. Instead, we can use ref counting (`Rc`) around the stored XPath so that cloning `MyXPath` clones the Rc (bumps the count). This would be both faster and save memory (although I'm not sure the later is much of an issue).

Although '1' will slow every build down a little, the times when it finds a match probably equalizes reading in most file and is a huge win in `unicode-full.yaml`. It's probably simpler/safer to implement also as it becomes self-contained in `MyXPath`.

Here's an example of range that deal with capitalization:
```
 - "𝘈-𝘡":    # 0x1d608 - 0x1d621
    - t: "italic"
    - test:
          if: "$SpeechOverrides_CapitalLetters = ''"
          then_test:
            if: "$Impairment = 'Blindness'"
            then: [t: "cap"]
          else: [x: "$SpeechOverrides_CapitalLetters"]
    - pitch:
        value: "$CapitalLetters_Pitch"
        replace: [spell: "translate('.', '𝘈𝘉𝘊𝘋𝘌𝘍𝘎𝘏𝘐𝘑𝘒𝘓𝘔𝘕𝘖𝘗𝘘𝘙𝘚𝘛𝘜𝘝𝘞𝘟𝘠𝘡', 'abcdefghijklmnopqrstuvwxyz')"]
```
The `if:`s, `x:`, and `value:` all involve XPaths (i.e., 4 total XPaths).  The actual substitution (`spell`) doesn't involve XPath.

Note: current startup/generation time for speech and braille of 
`"<math> <msup><mi>𝜴</mi> <mn>23</mn></msup></math>"`
is ~112ms - 120ms.
